### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by chippy99** [uecode/api-key-bundle#14]
Hi, followed your instructions for installation and have hit a problems
I am getting error that no authenication listener is registered for firewall auth
Any ideas ?

**Comment by L0rD59** [comment]
Hi,

Can you show us, your security.yml

thx,

**Comment by kmfk** [comment]
@chippy99 - I'm assuming you've resolved this issue. Closing this out, feel free to reopen if you are still having issues.
