### ISSUE TITLE
Exceptions being ignored by FOSRestBundle

### ISSUE THREAD

**Issue by henrypenny** [uecode/api-key-bundle#16]
I'm using this bundle with FOSRestBundle and FOSUserBundle.

In order to produce a JSON response to a failed authentication I've found that I need to modify:

`vendor/uecode/api-key-bundle/src/Uecode/Bundle/ApiKeyBundle/Security/Firewall/ApiKeyListener.php:73`

            //throw $failed;
            $message = $failed->getMessage();

Is this a bug, or should I not need to do this to get a JSON response?

**Comment by aequasi** [comment]
IIRC (i cant actually test this right now), leaving the thrown exception doesn't let you actually view the error.

You could write a listener, that gets called after that listener, and grab the event and turn it into json. Instead of editing core.
