### ISSUE TITLE
[question] Is it mandatory to require FOSUserBundle ~2.0@dev?

### ISSUE THREAD

**Issue by hanovruslan** [uecode/api-key-bundle#17]
Is it mandatory to require FOSUserBundle ~2.0@dev ? why not just last stable ~1.3 ?

**Comment by aequasi** [comment]
Throw up a PR and ill merge it in

**Comment by hanovruslan** [comment]
@aequasi that is not required anymore. 

I made [my own api key bundle](https://github.com/hanovruslan/api-key-bundle) and [demo project](https://github.com/hanovruslan/api-key-project) for that as well 

I did it from scratch but it totally inspired by yours ! Thanks a lot!
