### ISSUE TITLE
Remove FosUserBundle dependency

### ISSUE THREAD

**Issue by FlxPeters** [uecode/api-key-bundle#18]
Hi,

i'm working on a fork of this bundle to remove the FOSUserBundle dependency and just rely on Doctrine. Would you support it in this way? So i would make a Pull Request. Otherwise, I'll refactor it it my own Namespace and add some more stuff.

**Comment by aequasi** [comment]
If it still works when using FOSUserBundle, then yeah, I'll merge it in :)

**Comment by FlxPeters** [comment]
Thx for the quick reply. I made some tests and it seams not this easy as i thought. My current approach is to extract the services etc. in a base bundle and add the FOS integration as separate bundle on top. 

I need it in a private project, so i will make the kickstart in my own namespace, but i think we may could merch this bag when it's finished. 

What do you think about this approach?

**Comment by aequasi** [comment]
Maybe instead of an extension, make it a trait and an interface. It'd be a major version bump, but its alright

**Comment by hanovruslan** [comment]
@aequasi you must know that FOSUserBundle is not just user identity entity, this bundle also provides user manager (doctrine wrapper) and user provider (user model provider for security context)

i wonder for what reason you want to (have to?) get rid of FOSUserBundle?

Maybe you need just to minimize user identity property or smth like this?

**Comment by aequasi** [comment]
> @aequasi you must know that FOSUserBundle is not just user identity entity, this bundle also provides user manager (doctrine wrapper) and user provider (user model provider for security context)

@hanovruslan i am aware, yes. But the only dependency this bundle has on the FOSUserBundle is the [extended User model](https://github.com/uecode/api-key-bundle/blob/master/src/Uecode/Bundle/ApiKeyBundle/Model/ApiKeyUser.php#L5). You don't have to use Their user manager, or their user provider, and this bundle doesn't do anything with them either.

> i wonder for what reason you want to (have to?) get rid of FOSUserBundle?

Simply, the only reason it extended it in the first place, was because the project this was initially written for used FOSUserBundle. Now however, more people are looking to use this, but do not use FOSUserBundle. Its a hard dependency that shouldn't be necessary with horizontal inheritance.

**Comment by hanovruslan** [comment]
@aequasi  sorry, i put wrong nick into question )) 

> Its a hard dependency that shouldn't be necessary

Exact manager shouldn't be necessary, that's right, but app has to be coupled with some of user manager. and as a group of user related services FOSUserBundle acts like adapter between security context and data layer. So if you replace it with any other service(s) then your app\services and  will be  tight coupled with your bundle ... so it's like to give tit for tat

**Comment by FlxPeters** [comment]
> i wonder for what reason you want to (have to?) get rid of FOSUserBundle?

Simply, i don't use FOSUserBundle but need an API key authentication. This Bundle does this job real good. 

Yes, it will be a major change. My current version is something like a base bundle. You have to define your own Entity and UserProvider (in most cases this would be a Doctrine Repo). This Entity must implement a Interface to get and set the api key. A Doctrine Listener checks all Classes implementing  this Interface on preUpdate and prePersist for an api key and generates a new one if necessary. 

You can now add concrete implementations for FOSRestBundle as a separate Bundle or add this classes to this base Bundle. I prefer a second Bundle, because you can define a concrete FOSUserBundle dependency. Otherwise you can just add it as hint in composer.

**Comment by hanovruslan** [comment]
@FlxPeters yep. that's what i expected to hear ) in my own project that also has to listen to api key i set api key as a stand-alone entity so app services (security context generally) interact with it via separate provider and manager as well. thus app does not depend on FOSUserBundle and it's services like user provider.

**Comment by FlxPeters** [comment]
@hanovruslan  So you are ok with that approach? I have to make some tests, fixes and doc in my repo. when i'm ready you can have a look at it and give me feedback if this fits your requirements.

**Comment by hanovruslan** [comment]
@FlxPeters i definitely interested in your implementation of this issue but you can do what you to because i already have my implementation )

**Comment by aequasi** [comment]
@FlxPeters that would definitely work. That way it would work with any user implementation.

**Comment by gepo** [comment]
I think PR #22 is about this issue.

**Comment by aequasi** [comment]
Solved by #22
