### ISSUE TITLE
Get user via apikey

### ISSUE THREAD

**Issue by meron1122** [uecode/api-key-bundle#20]
How to from controller get user related with apikey for current request?

**Comment by aequasi** [comment]
Same way you normally would with symfony



—
Aaron Scherer
http://bldr.io/

**Comment by georgesamy** [comment]
I have the same issue. @aequasi what would be the "normal" way to do it please?

**Comment by georgesamy** [comment]
@aequasi nvm my bad.

$user = $this->get('security.context')->getToken()->getUser()
